package com.filip.smartlifesaver.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Patient")
public class Patient {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String deviceID;

    @DynamoDBAttribute
    private String thingId;

    @DynamoDBAttribute
    private int warningsCount;


    /**
     * THE ATTRIBUTES BELOW ARE DISPLAYING THE LAST REPORTED INFORMATION ABOUT PATIENT
     */

    /**
     * resting blood pressure (in mm Hg)
     */
    @DynamoDBAttribute
    private int lastMeasuredTestBPS;

    /**
     * serum cholestoral in mg/dl
     */
    @DynamoDBAttribute
    private int lastMeasuredCholesterol;

    /**
     * lastMeasuredThalach: maximum heart rate achieved
     */
    @DynamoDBAttribute
    private int lastMeasuredThalach;


    /**
     * (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)
     */
    @DynamoDBAttribute
    private boolean lastMeasuredMuchFBS;


    public Patient() {

    }

}
